on:
    push:
        branches:
            - main
name: "Build and Deploy"
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.35.3
            - run: flutter --version
            - run: flutter pub get
            - run: flutter build web --base-href="/flutter_resume/"
            - name: Upload production-ready build files
              uses: actions/upload-artifact@v4
              with:
                name: production-files
                path: ./build/web
            - name: Push to Releases
              uses: ncipollo/release-action@v1
              with:
                  artifacts: build/web/**
                  tag: deploy-${{ github.run_number }}
                  name: Deploy ${{ github.run_number }}
                  draft: false
                  prerelease: false
    
    deploy: 
        name: Deploy to GitHub Pages
        environment: 
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        needs: build
        runs-on: ubuntu-latest
        if: github.ref == 'refs/heads/main'
        permissions:
            contents: write
            pages: write
            id-token: write    
        steps:
            - name: Download artifact
              uses: actions/download-artifact@v4
              with:
                name: production-files
                path: ./build
            - name: Deploy to gh-pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./build
