on:
    push:
        branches:
            - main
name: "Build and Deploy"
jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Set up Flutter
              uses: subosito/flutter-action@v2
              with:
                  channel: stable
                  flutter-version: 3.35.3
            - run: flutter --version
            - run: flutter pub get
            - run: flutter build web
