name: GH Pages Test

on: 
    push: 
        branches: [ main ]

permissions: 
    contents: write

jobs: 
    build: 
        runs-on: ubuntu-latest

        steps: 
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
            - uses: bluefireteam/flutter-gh-pages@v9
              with: 
                baseHref: /flutter-resume/
